# Generated by Django 5.2 on 2025-07-13 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(verbose_name='試験日')),
                ('mix_name', models.CharField(max_length=255, verbose_name='配合名')),
                ('water_cement_ratio', models.FloatField(verbose_name='水セメント比')),
                ('sand_aggregate_ratio', models.FloatField(verbose_name='S/A')),
                ('air_content_percent', models.FloatField(verbose_name='空気量(%)')),
                ('w_value', models.FloatField(verbose_name='W')),
                ('n_value', models.FloatField(verbose_name='N')),
                ('h_value', models.FloatField(verbose_name='H')),
                ('m_value', models.FloatField(verbose_name='M')),
                ('l_value', models.FloatField(verbose_name='L')),
                ('s_value', models.FloatField(verbose_name='S')),
                ('g_value', models.FloatField(verbose_name='G')),
                ('slump', models.FloatField(blank=True, null=True, verbose_name='スランプ(mm)')),
                ('air_content_result', models.FloatField(verbose_name='測定空気量(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '試験結果',
                'verbose_name_plural': '試験結果',
                'ordering': ['-test_date'],
            },
        ),
    ]
